region      = "enter-your-region-here"
access_key  = "enter-your-access-key-here"
secret_key  = "enter-your-secret-key-here"
project     = "enter-name-of-your-project"
vpc_cidr    = "X.X.X.X/X"
vpc_subnets = "enter required number"
